# default values
all:
  title_prefix: "The Registry! :: "
  base_domain:         "http://registry.dev/uri/"
  default_language: en
  default_status_id: 1
  default_conneg_type: rdf
  schema_profile_id: 1
# these values may be edited for a localized install
  admin_email:       sysadmin@metadataregistry.org
  mysql_command:       /usr/bin/mysql
  mysqldump_command:   /usr/bin/mysqldump
  db_load_filename:    swregistry_test_dump.sql
