rendering: ~
web_debug: ~

userObject:
  class: userObjectFilter
  param:
    condition:   %APP_USER_OBJECT%

security:  ~
# generally, you will want to insert your own filters here
referrer:
  class: sfRefererFilter
  
cache:     ~
common:    ~
flash:     ~
execution: ~
