all:
  stylesheets: [conceptprop/layout]
  javascripts: [%SF_PROTOTYPE_WEB_DIR%/js/prototype: { position: last }]

editSuccess:
  javascripts: [conceptprop/swapoptions: { position: last }]

searchSuccess:
  stylesheets: -*
